### ISSUE TITLE
Use PHPSESSION not work.

### ISSUE THREAD

**Issue by abserari** [NateScarlet/pixiv#17]
![image](https://user-images.githubusercontent.com/32089134/103476022-35322a00-4ded-11eb-94c0-bde9afaf6818.png)

when use login by username and password, cookies add a lot. Need to pass more cookies?
![image](https://user-images.githubusercontent.com/32089134/103476092-bc7f9d80-4ded-11eb-8d86-6aa2b023205b.png)

**Comment by NateScarlet** [comment]
artwork rank not require login,  and tested daily by github ci
https://github.com/NateScarlet/pixiv/blob/d277aff0b61013f777c6a49898435bdf5513ecba/pkg/artwork/rank_test.go#L21

**Comment by NateScarlet** [comment]
What you got when run `curl https://www.pixiv.net/ranking.php?format=json` ?

**Comment by abserari** [comment]
when I use t78e7raoq5ma3q32emf0o68qh514l78c, the PHPSESSIONID from the terminal, it works.
the PHPSESSION is from my edge browser which is not work in the first picture.

I test curl https://www.pixiv.net/ranking.php?format=json, ok .

**Comment by abserari** [comment]
One more question. I couldn't get this url. `curl "https://www.pixiv.net/ranking.php?format=json&mode=daily_r18"`

But I could get it by browser with my pixiv account is log in.

**Comment by NateScarlet** [comment]
r18 data require login as a account that choose to display r-18 contents in https://www.pixiv.net/setting_user.php

**Comment by NateScarlet** [comment]
You can test client login status by 
https://github.com/NateScarlet/pixiv/blob/d277aff0b61013f777c6a49898435bdf5513ecba/pkg/client/auth.go#L15

**Comment by abserari** [comment]
> r18 data require login as a account that choose to display r-18 contents in https://www.pixiv.net/setting_user.php
![image](https://user-images.githubusercontent.com/32089134/103476540-cdcaa900-4df1-11eb-9e1a-15754bea6909.png)

I think I set it true.

And I test the client login status. It is false.

**Comment by NateScarlet** [comment]
似乎是P站更新了登录检测机制 我研究下

**Comment by NateScarlet** [comment]
现在会检测User-Agent了 我更新下库

**Comment by NateScarlet** [comment]
用 0.4.1 应该就行了

**Comment by abserari** [comment]
ok,  Default

**Comment by NateScarlet** [comment]
你应该主动登出一次把发在这的 PHPSESSID 过期掉 不然可能你账号可能会被其他人使用
